name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.4.1
  pull_to_refresh: ^2.0.0
  flutter_inappwebview: ^6.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  mocktail: ^1.0.4
 
flutter:
  uses-material-design: true

  assets:
    - assets/images/noimage.jpg
    - assets/images/rick_morti.jpg
    - assets/images/bgs.jpg
